# Access to shop directory database
notion:
  api-url: "https://api.notion.com/v1/databases/"
  version: "2022-06-28"
  api-key: ""
  database: ""

# Frequency in which the local data is updated
update-frequency: 600000 # In Milliseconds