name: ShopLookup
version: '1.0-SNAPSHOT'
main: io.github.branhardy.shopLookup.ShopLookup
api-version: '1.21'

commands:
  shop:
    description: "Get a list of shops selling the specified item"
    usage: "/shop [item]"
